# Generated by Django 4.2.1 on 2023-05-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='paymentinvoice',
            name='car_number',
        ),
        migrations.RemoveField(
            model_name='paymentinvoice',
            name='debt',
        ),
        migrations.AddField(
            model_name='car',
            name='clients',
            field=models.ManyToManyField(related_name='cars', to='MyApp.client'),
        ),
        migrations.AddField(
            model_name='car',
            name='debt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_space', to='MyApp.car'),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='MyApp.car'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
