# Generated by Django 4.2.1 on 2023-09-17 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_coupon_employee_news_question_review_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
